os:
  - linux
  - osx
language: r
cache: packages
use_bioc: true
bioc_required: true
r: bioc-release
before_install:
    - Rscript -e 'source(file = "http://bioconductor.org/biocLite.R");useDevel(devel = TRUE);biocLite(pkgs = c("BiocParallel", "Biostrings", "ensembldb", "ensemblVEP", "GenomeInfoDb", "GenomicRanges", "ggplot2", "IRanges", "reshape2", "Rsamtools", "S4Vectors", "SummarizedExperiment", "VariantAnnotation"))'
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tlmgr install bera nowidow parnotes marginfix; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo tlmgr install titling; fi
warnings_are_errors: false
sudo: required
r_github_packages:
    - rstudio/shiny
    - rstudio/DT
r_build_args: --keep-empty-dirs --no-resave-data
r_check_args: --no-vignettes --timings

after_success:
    - Rscript -e 'covr::codecov()'
