
language: r
use_bioc: true
bioc_required: true
r: bioc-release

os:
  - linux
  - osx

before_install:
    - Rscript -e 'source(file = "http://bioconductor.org/biocLite.R");tryCatch(useDevel(devel = TRUE), error = function(err){message(err)})'
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tlmgr update --all; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo tlmgr update --all; fi

warnings_are_errors: false

r_github_packages:
    - rstudio/shiny
    - rstudio/DT
    - Bioconductor-mirror/BiocStyle
    - Bioconductor-mirror/S4Vectors

r_build_args: --keep-empty-dirs --no-resave-data
r_check_args: --no-vignettes --timings

after_success:
    - Rscript -e 'covr::codecov()'
