# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-devel
cache: packages

os:
    - osx
    - linux

r_check_args: --no-build-vignettes
bioc_use_devel: true

addons:
  apt:
    packages:
        

before_install:
    - tlmgr install bera
    - R CMD Rscript -e 'source(file = "http://bioconductor.org/biocLite.R");useDevel(devel = TRUE)'

r_packages: DT
r_github_packages: rstudio/DT
