# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-devel
cache: packages

os:
    - osx
    - linux

r_check_args: --no-build-vignettes
use_bioc: true
bioc_use_devel: true

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tlmgr install bera nowidow parnotes; fi

#r_github_packages: rstudio/DT
