# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

environment:
  global:
    WARNINGS_ARE_ERRORS: 1
    _R_CHECK_FORCE_SUGGESTS_: 0
    # USE_RTOOLS: true ## to be able to use Remotes (i.e. non-CRAN sources)

  matrix:
    - R_VERSION: devel
      R_ARCH: x64

    - R_VERSION: devel
      R_ARCH: i386

    #- R_VERSION: devel
    #  R_ARCH: x64
    #  GCC_PATH: mingw_64
    #  BIOC_USE_DEVEL: TRUE
    #  R_CHECK_ARGS: "--no-vignettes --timings"
    #  R_BUILD_ARGS: "--keep-empty-dirs --no-resave-data"

#branches:
#  only:
#    - master

#cache:
  #- C:\RLibrary

build_script:
  - echo Current directory=%CD%
  - travis-tool.sh install_bioc_deps
  #- Rscript -e 'BiocInstaller::biocValid(fix=TRUE)'
  #- Rscript -e 'print(c);showMethods(\"c\", classes = \"GenomicRanges\", includeDefs = TRUE)'
  #- Rscript -e 'library(GenomicRanges);print(c);showMethods(\"\c", classes = \"GenomicRanges\", includeDefs = TRUE)'
  #- travis-tool.sh install_bioc ensemblVEP EnsDb.Hsapiens.v75

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
